### ISSUE TITLE
 Issue/Non-intuitive behavior of vector with non-empty initialization

### ISSUE THREAD

**Issue by alexanderscheible** [kamchatka-volcano/figcone#22]
There seems to be an issue/non-intuitive behavior when defining an optional parameter vector with non-empty default values, e.g., like in

Params.hpp
```
struct Params {
  std::vector<double> weights {0.8, 0.2};
  using traits = figcone::FieldTraits<figcone::OptionalField<&Params::weights>>;
};
```
When I do not provide special values for weights, everything is fine, but when I specify the weights, the default weights are not removed, but the special values are appended.

Params.yaml
```
Params:
  weights: [5, 6]
```

This will result in weights == {0.8, 0.2, 5, 6}

**Comment by kamchatka-volcano** [comment]
Hi, thanks for creating this issue. This behavior was definitely unintended; not sure how it slipped through the test cases.
The fix is trivial, so I’ve already released it in [v3.2.0](https://github.com/kamchatka-volcano/figcone/releases/tag/v3.2.0). Please update.
