### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by MeanSquaredError** [kamchatka-volcano/figcone#8]
Thank you for writing such a useful library. There is a slight problem with the error that is thrown when the library tries to load a non-existent file. E.g.
```
auto reader = figcone::ConfigReader {};
reader.readYamlFile<config_struct> ("non_existent.yaml");
```

It will say something along the lines of
```
terminate called after throwing an instance of 'figcone::ConfigError'
  what():  [line:1, column:1] Root node: Node 'database' is missing.
Aborted (core dumped)
```

The text in the `figcone::ConfigError` is misleading because it makes the user believe that the library opened the config file, but the file is not structured correctly. It should actually say that it could not find/open the configuration file.

**Comment by kamchatka-volcano** [comment]
Hi! Thanks for bringing it to my attention. I was aware that the file opening was done sloppily, but I forgot to fix it. I'll try to work on it as soon as possible.

**Comment by kamchatka-volcano** [comment]
@MeanSquaredError I've added some checks with better error messages, please update to [v2.4.7](https://github.com/kamchatka-volcano/figcone/releases/tag/v2.4.7)

**Comment by MeanSquaredError** [comment]
@kamchatka-volcano 
Thank you!
